version: 0.0
os: linux

files:
  - source: /
    destination: /opt/wildfly/standalone/deployments

hooks:
    ApplicationStop:
    - location: stop.sh
      timeout: 300
      runas: root
    ApplicationStart:
    - location: start.sh
      timeout: 300
      runas: root

permissions:
  - object: /
    pattern: "**"
    owner: ubuntu
    group: ubuntu
